// <auto-generated />
using InvigilatorSchedulerStandard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvigilatorScheduler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("InvigilatorsOverride")
                        .HasColumnType("int");

                    b.Property<int>("SessionIndex")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.RuleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RuleConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SETTINGS",
                            JsonValue = "{\"defaultInvigilatorsPerExam\":2,\"backupInvigilatorsPerDay\":1,\"randomSeed\":5,\"fairnessEnabled\":true}"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NO_EXAM_FOR_BACKUP_SAME_DAY",
                            JsonValue = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MAX_SESSIONS_PER_TEACHER_PER_DAY",
                            JsonValue = "{\"value\":2}"
                        });
                });

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.TeacherRestrictedExamSession", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "ExamSessionId");

                    b.HasIndex("ExamSessionId");

                    b.ToTable("TeacherRestrictedExamSessions");
                });

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.TeacherRestrictedExamSession", b =>
                {
                    b.HasOne("InvigilatorSchedulerStandard.Data.ExamSession", "ExamSession")
                        .WithMany()
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvigilatorSchedulerStandard.Data.Teacher", "Teacher")
                        .WithMany("RestrictedExamSessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InvigilatorSchedulerStandard.Data.Teacher", b =>
                {
                    b.Navigation("RestrictedExamSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
